// src/lib/components/UserAvatar.svelte
<script lang="ts">
  import { Avatar, AvatarFallback } from '$lib/components/ui/avatar';
  import { getPreset, initialsColor } from '$lib/avatars';
  import { shortName } from '$lib/utils/user';

  interface Props {
    avatarKey?: string | null;
    displayName: string;
    size?: 'xs' | 'sm' | 'md';
  }

  let { avatarKey = null, displayName, size = 'sm' }: Props = $props();

  const sizeClass = { xs: 'size-5 text-[10px]', sm: 'size-7 text-xs', md: 'size-9 text-sm' };

  const preset = $derived(getPreset(avatarKey));
  const fallbackColor = $derived(initialsColor(displayName));
  const initials = $derived(shortName(displayName) || '?');
</script>

<Avatar class={sizeClass[size]}>
  {#if preset}
    <AvatarFallback style="background:{preset.bg}; color:#fff; font-size:inherit;">
      {preset.emoji}
    </AvatarFallback>
  {:else}
    <AvatarFallback style="background:{fallbackColor}; color:#fff; font-size:inherit;">
      {initials}
    </AvatarFallback>
  {/if}
</Avatar>

// mobile/src/components/user-avatar.tsx
// Preset-emoji avatar with initials fallback — mobile port of UserAvatar.svelte.
import { StyleSheet, Text, View } from 'react-native';

import { getPreset, initialsColor, shortName } from '@/domain/avatars';

const SIZES = {
  sm: { circle: 28, font: 12 },
  md: { circle: 36, font: 14 },
  lg: { circle: 56, font: 22 }
} as const;

export type UserAvatarProps = {
  avatarKey?: string | null;
  displayName: string | null;
  size?: keyof typeof SIZES;
};

export function UserAvatar({ avatarKey, displayName, size = 'sm' }: UserAvatarProps) {
  const preset = getPreset(avatarKey);
  const name = displayName ?? '';
  const dims = SIZES[size];
  const background = preset ? preset.bg : initialsColor(name);
  const label = preset ? preset.emoji : shortName(name) || '?';

  return (
    <View
      style={[
        styles.circle,
        {
          width: dims.circle,
          height: dims.circle,
          borderRadius: dims.circle / 2,
          backgroundColor: background
        }
      ]}
    >
      <Text style={[styles.label, { fontSize: dims.font }]}>{label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  circle: {
    alignItems: 'center',
    justifyContent: 'center'
  },
  label: {
    color: '#ffffff',
    fontWeight: '700'
  }
});
